/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    Basic: (typeof import("./src/components/UserInfo/Basic.vue"))["default"];
    ChangeAvatar: (typeof import("./src/components/UserInfo/ChangeAvatar.vue"))["default"];
    ChangePwd: (typeof import("./src/components/UserInfo/ChangePwd.vue"))["default"];
    DeleteUser: (typeof import("./src/components/UserInfo/DeleteUser.vue"))["default"];
    Dicts: (typeof import("./src/components/Dicts/Dicts.vue"))["default"];
    ElAlert: (typeof import("element-plus/es"))["ElAlert"];
    ElAside: (typeof import("element-plus/es"))["ElAside"];
    ElAvatar: (typeof import("element-plus/es"))["ElAvatar"];
    ElButton: (typeof import("element-plus/es"))["ElButton"];
    ElCard: (typeof import("element-plus/es"))["ElCard"];
    ElCheckbox: (typeof import("element-plus/es"))["ElCheckbox"];
    ElCol: (typeof import("element-plus/es"))["ElCol"];
    ElContainer: (typeof import("element-plus/es"))["ElContainer"];
    ElDialog: (typeof import("element-plus/es"))["ElDialog"];
    ElDivider: (typeof import("element-plus/es"))["ElDivider"];
    ElFooter: (typeof import("element-plus/es"))["ElFooter"];
    ElForm: (typeof import("element-plus/es"))["ElForm"];
    ElFormItem: (typeof import("element-plus/es"))["ElFormItem"];
    ElInput: (typeof import("element-plus/es"))["ElInput"];
    ElInputNumber: (typeof import("element-plus/es"))["ElInputNumber"];
    ElMain: (typeof import("element-plus/es"))["ElMain"];
    ElMenu: (typeof import("element-plus/es"))["ElMenu"];
    ElMenuItem: (typeof import("element-plus/es"))["ElMenuItem"];
    ElOption: (typeof import("element-plus/es"))["ElOption"];
    ElPagination: (typeof import("element-plus/es"))["ElPagination"];
    ElProgress: (typeof import("element-plus/es"))["ElProgress"];
    ElResult: (typeof import("element-plus/es"))["ElResult"];
    ElRow: (typeof import("element-plus/es"))["ElRow"];
    ElSelect: (typeof import("element-plus/es"))["ElSelect"];
    ElSlider: (typeof import("element-plus/es"))["ElSlider"];
    ElSubMenu: (typeof import("element-plus/es"))["ElSubMenu"];
    ElSwitch: (typeof import("element-plus/es"))["ElSwitch"];
    ElTooltip: (typeof import("element-plus/es"))["ElTooltip"];
    Learn: (typeof import("./src/components/Learn.vue"))["default"];
    Login: (typeof import("./src/components/Login.vue"))["default"];
    Options: (typeof import("./src/components/Options.vue"))["default"];
    Register: (typeof import("./src/components/Register.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    Stats: (typeof import("./src/components/Stats.vue"))["default"];
    UserInfo: (typeof import("./src/components/UserInfo/UserInfo.vue"))["default"];
    WordCard: (typeof import("./src/components/WordCard.vue"))["default"];
  }
}
