# SPDX-FileCopyrightText: 2024 WordHub Organization <integral@member.fsf.org>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: docker build
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build
        run: |
          docker buildx build . -t wordhub
